### PR TITLE
Fix parsing error when in-tag string content contains `>`

### LINKED ISSUE #995: Angle brackets in helper string argument terminates tag early and duplicates remaining tag text
Recently, when working on a codemod I ran into an issue where some of our code had angle brackets in the string argument to a helper in a component argument. The resulting output incorrectly terminates this tag and duplicates a portion of the tag after the closing bracket. Here's an example test that will fail:

```
test('issue can handle angle brackets in modifier argument values', function () {
  let template = `
    <Select
      @placeholder={{do-something ">> Some Text Here"}}
      @options={{this.items}}
      as |item|
    >
      {{item.name}}
    </Select>
  `;
  let ast = parse(template);
  traverse(ast, {
    ElementNode(node) {
      node.tag = `${node.tag}`;
    },
  });
  expect(print(ast)).toEqual(template);
});
```

I've included a `traverse` call with an artificial modification to trigger the issue. Even though nothing is really changed the output is as follows:

```
<Select
  @placeholder={{do-something ">> Some Text Here"}}
  @options={{this.items}}
  as |item|>> Some Text Here"}}
  @options={{this.items}}
  as |item|>
  {{item.name}}
</Select>
```

Note here the tag gets closed after `as |item` and immediately followed by the 2nd angle bracket from the `do-something` string argument and the remainder of the opening tag: `as |item|>> Some Text Here"}}`.

### PR DESCRIPTION
**Pull request by rgallagherab**
Resolves an issue where an `ElementNode` with block params can be prematurely terminated if a right angle bracket (`>`) is included in a string before the true closing bracket.

fixes #995

### CODE REVIEW

File: src/parse-result.ts [hunk 1]
```diff
@@ -513,7 +513,10 @@ export default class ParseResult {
               blockParamsEndIndex + 1
             );
 
-            const closeOpenIndex = nodeInfo.source.indexOf(selfClosing ? '/>' : '>');
+            // Match closing index after start of block params to avoid closing tag if /> or > encountered in string
```
Comment (rgallagherab) [inline src/parse-result.ts:516]: I'm assuming that since this is inside of an `if` statement for when block params are present we can trust that the closing bracket will never be before the starting point of the block param?

**Review by lifeart — APPROVED** [review]

**Review by NullVoxPopuli — APPROVED** [review]

**Comment by bmish** [comment]
Can you add a descriptive PR title?
